apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/alx-test-org/jx-angular-quick:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/alx-test-org/jx-angular-quick:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-angular-quick
        chartPath: charts/jx-angular-quick
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/alx-test-org/jx-angular-quick"
          image.tag: "{{.DIGEST_HEX}}"
